/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SSiteSlugIndexRouteImport } from './routes/s.$siteSlug.index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as SSiteSlugSplatRouteImport } from './routes/s.$siteSlug.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as SSiteSlugShopIndexRouteImport } from './routes/s.$siteSlug.shop.index'
import { Route as SSiteSlugBlogIndexRouteImport } from './routes/s.$siteSlug.blog.index'
import { Route as SSiteSlugShopSlugRouteImport } from './routes/s.$siteSlug.shop.$slug'
import { Route as SSiteSlugFFormKeyRouteImport } from './routes/s.$siteSlug.f.$formKey'
import { Route as SSiteSlugBlogSlugRouteImport } from './routes/s.$siteSlug.blog.$slug'
import { Route as AuthenticatedSitesSiteIdEditRouteImport } from './routes/_authenticated/sites.$siteId.edit'
import { Route as AuthenticatedSitesSiteIdWorkflowsIndexRouteImport } from './routes/_authenticated/sites.$siteId.workflows.index'
import { Route as AuthenticatedSitesSiteIdProductsIndexRouteImport } from './routes/_authenticated/sites.$siteId.products.index'
import { Route as AuthenticatedSitesSiteIdPagesIndexRouteImport } from './routes/_authenticated/sites.$siteId.pages.index'
import { Route as AuthenticatedSitesSiteIdOrdersIndexRouteImport } from './routes/_authenticated/sites.$siteId.orders.index'
import { Route as AuthenticatedSitesSiteIdMenusIndexRouteImport } from './routes/_authenticated/sites.$siteId.menus.index'
import { Route as AuthenticatedSitesSiteIdFormsIndexRouteImport } from './routes/_authenticated/sites.$siteId.forms.index'
import { Route as AuthenticatedSitesSiteIdBlogIndexRouteImport } from './routes/_authenticated/sites.$siteId.blog.index'
import { Route as AuthenticatedSitesSiteIdProductsProductIdEditRouteImport } from './routes/_authenticated/sites.$siteId.products.$productId.edit'
import { Route as AuthenticatedSitesSiteIdPagesPageIdEditRouteImport } from './routes/_authenticated/sites.$siteId.pages.$pageId.edit'
import { Route as AuthenticatedSitesSiteIdFormsFormIdSubmissionsRouteImport } from './routes/_authenticated/sites.$siteId.forms.$formId.submissions'
import { Route as AuthenticatedSitesSiteIdFormsFormIdEditRouteImport } from './routes/_authenticated/sites.$siteId.forms.$formId.edit'
import { Route as AuthenticatedSitesSiteIdBlogPostIdEditRouteImport } from './routes/_authenticated/sites.$siteId.blog.$postId.edit'
import { Route as AuthenticatedSitesSiteIdWorkflowsIndexRouteImport } from './routes/_authenticated/sites.$siteId.workflows.index'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SSiteSlugIndexRoute = SSiteSlugIndexRouteImport.update({
  id: '/s/$siteSlug/',
  path: '/s/$siteSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const SSiteSlugSplatRoute = SSiteSlugSplatRouteImport.update({
  id: '/s/$siteSlug/$',
  path: '/s/$siteSlug/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SSiteSlugShopIndexRoute = SSiteSlugShopIndexRouteImport.update({
  id: '/s/$siteSlug/shop/',
  path: '/s/$siteSlug/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const SSiteSlugBlogIndexRoute = SSiteSlugBlogIndexRouteImport.update({
  id: '/s/$siteSlug/blog/',
  path: '/s/$siteSlug/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const SSiteSlugShopSlugRoute = SSiteSlugShopSlugRouteImport.update({
  id: '/s/$siteSlug/shop/$slug',
  path: '/s/$siteSlug/shop/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SSiteSlugFFormKeyRoute = SSiteSlugFFormKeyRouteImport.update({
  id: '/s/$siteSlug/f/$formKey',
  path: '/s/$siteSlug/f/$formKey',
  getParentRoute: () => rootRouteImport,
} as any)
const SSiteSlugBlogSlugRoute = SSiteSlugBlogSlugRouteImport.update({
  id: '/s/$siteSlug/blog/$slug',
  path: '/s/$siteSlug/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSitesSiteIdEditRoute =
  AuthenticatedSitesSiteIdEditRouteImport.update({
    id: '/sites/$siteId/edit',
    path: '/sites/$siteId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSitesSiteIdWorkflowsIndexRoute =
  AuthenticatedSitesSiteIdWorkflowsIndexRouteImport.update({
    id: '/sites/$siteId/workflows/',
    path: '/sites/$siteId/workflows/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSitesSiteIdProductsIndexRoute =
  AuthenticatedSitesSiteIdProductsIndexRouteImport.update({
    id: '/sites/$siteId/products/',
    path: '/sites/$siteId/products/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSitesSiteIdPagesIndexRoute =
  AuthenticatedSitesSiteIdPagesIndexRouteImport.update({
    id: '/sites/$siteId/pages/',
    path: '/sites/$siteId/pages/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSitesSiteIdOrdersIndexRoute =
  AuthenticatedSitesSiteIdOrdersIndexRouteImport.update({
    id: '/sites/$siteId/orders/',
    path: '/sites/$siteId/orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSitesSiteIdMenusIndexRoute =
  AuthenticatedSitesSiteIdMenusIndexRouteImport.update({
    id: '/sites/$siteId/menus/',
    path: '/sites/$siteId/menus/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSitesSiteIdFormsIndexRoute =
  AuthenticatedSitesSiteIdFormsIndexRouteImport.update({
    id: '/sites/$siteId/forms/',
    path: '/sites/$siteId/forms/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSitesSiteIdBlogIndexRoute =
  AuthenticatedSitesSiteIdBlogIndexRouteImport.update({
    id: '/sites/$siteId/blog/',
    path: '/sites/$siteId/blog/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSitesSiteIdWorkflowsIndexRoute =
  AuthenticatedSitesSiteIdWorkflowsIndexRouteImport.update({
    id: '/sites/$siteId/workflows/',
    path: '/sites/$siteId/workflows/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSitesSiteIdProductsProductIdEditRoute =
  AuthenticatedSitesSiteIdProductsProductIdEditRouteImport.update({
    id: '/sites/$siteId/products/$productId/edit',
    path: '/sites/$siteId/products/$productId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSitesSiteIdPagesPageIdEditRoute =
  AuthenticatedSitesSiteIdPagesPageIdEditRouteImport.update({
    id: '/sites/$siteId/pages/$pageId/edit',
    path: '/sites/$siteId/pages/$pageId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSitesSiteIdFormsFormIdSubmissionsRoute =
  AuthenticatedSitesSiteIdFormsFormIdSubmissionsRouteImport.update({
    id: '/sites/$siteId/forms/$formId/submissions',
    path: '/sites/$siteId/forms/$formId/submissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSitesSiteIdFormsFormIdEditRoute =
  AuthenticatedSitesSiteIdFormsFormIdEditRouteImport.update({
    id: '/sites/$siteId/forms/$formId/edit',
    path: '/sites/$siteId/forms/$formId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSitesSiteIdBlogPostIdEditRoute =
  AuthenticatedSitesSiteIdBlogPostIdEditRouteImport.update({
    id: '/sites/$siteId/blog/$postId/edit',
    path: '/sites/$siteId/blog/$postId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/s/$siteSlug/$': typeof SSiteSlugSplatRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/s/$siteSlug/': typeof SSiteSlugIndexRoute
  '/sites/$siteId/edit': typeof AuthenticatedSitesSiteIdEditRoute
  '/s/$siteSlug/blog/$slug': typeof SSiteSlugBlogSlugRoute
  '/s/$siteSlug/f/$formKey': typeof SSiteSlugFFormKeyRoute
  '/s/$siteSlug/shop/$slug': typeof SSiteSlugShopSlugRoute
  '/s/$siteSlug/blog/': typeof SSiteSlugBlogIndexRoute
  '/s/$siteSlug/shop/': typeof SSiteSlugShopIndexRoute
  '/sites/$siteId/blog/': typeof AuthenticatedSitesSiteIdBlogIndexRoute
  '/sites/$siteId/forms/': typeof AuthenticatedSitesSiteIdFormsIndexRoute
  '/sites/$siteId/menus/': typeof AuthenticatedSitesSiteIdMenusIndexRoute
  '/sites/$siteId/orders/': typeof AuthenticatedSitesSiteIdOrdersIndexRoute
  '/sites/$siteId/pages/': typeof AuthenticatedSitesSiteIdPagesIndexRoute
  '/sites/$siteId/products/': typeof AuthenticatedSitesSiteIdProductsIndexRoute
  '/sites/$siteId/workflows/': typeof AuthenticatedSitesSiteIdWorkflowsIndexRoute
  '/sites/$siteId/blog/$postId/edit': typeof AuthenticatedSitesSiteIdBlogPostIdEditRoute
  '/sites/$siteId/forms/$formId/edit': typeof AuthenticatedSitesSiteIdFormsFormIdEditRoute
  '/sites/$siteId/forms/$formId/submissions': typeof AuthenticatedSitesSiteIdFormsFormIdSubmissionsRoute
  '/sites/$siteId/pages/$pageId/edit': typeof AuthenticatedSitesSiteIdPagesPageIdEditRoute
  '/sites/$siteId/products/$productId/edit': typeof AuthenticatedSitesSiteIdProductsProductIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/s/$siteSlug/$': typeof SSiteSlugSplatRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/s/$siteSlug': typeof SSiteSlugIndexRoute
  '/sites/$siteId/edit': typeof AuthenticatedSitesSiteIdEditRoute
  '/s/$siteSlug/blog/$slug': typeof SSiteSlugBlogSlugRoute
  '/s/$siteSlug/f/$formKey': typeof SSiteSlugFFormKeyRoute
  '/s/$siteSlug/shop/$slug': typeof SSiteSlugShopSlugRoute
  '/s/$siteSlug/blog': typeof SSiteSlugBlogIndexRoute
  '/s/$siteSlug/shop': typeof SSiteSlugShopIndexRoute
  '/sites/$siteId/blog': typeof AuthenticatedSitesSiteIdBlogIndexRoute
  '/sites/$siteId/forms': typeof AuthenticatedSitesSiteIdFormsIndexRoute
  '/sites/$siteId/menus': typeof AuthenticatedSitesSiteIdMenusIndexRoute
  '/sites/$siteId/orders': typeof AuthenticatedSitesSiteIdOrdersIndexRoute
  '/sites/$siteId/pages': typeof AuthenticatedSitesSiteIdPagesIndexRoute
  '/sites/$siteId/products': typeof AuthenticatedSitesSiteIdProductsIndexRoute
  '/sites/$siteId/workflows': typeof AuthenticatedSitesSiteIdWorkflowsIndexRoute
  '/sites/$siteId/blog/$postId/edit': typeof AuthenticatedSitesSiteIdBlogPostIdEditRoute
  '/sites/$siteId/forms/$formId/edit': typeof AuthenticatedSitesSiteIdFormsFormIdEditRoute
  '/sites/$siteId/forms/$formId/submissions': typeof AuthenticatedSitesSiteIdFormsFormIdSubmissionsRoute
  '/sites/$siteId/pages/$pageId/edit': typeof AuthenticatedSitesSiteIdPagesPageIdEditRoute
  '/sites/$siteId/products/$productId/edit': typeof AuthenticatedSitesSiteIdProductsProductIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/s/$siteSlug/$': typeof SSiteSlugSplatRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/s/$siteSlug/': typeof SSiteSlugIndexRoute
  '/_authenticated/sites/$siteId/edit': typeof AuthenticatedSitesSiteIdEditRoute
  '/s/$siteSlug/blog/$slug': typeof SSiteSlugBlogSlugRoute
  '/s/$siteSlug/f/$formKey': typeof SSiteSlugFFormKeyRoute
  '/s/$siteSlug/shop/$slug': typeof SSiteSlugShopSlugRoute
  '/s/$siteSlug/blog/': typeof SSiteSlugBlogIndexRoute
  '/s/$siteSlug/shop/': typeof SSiteSlugShopIndexRoute
  '/_authenticated/sites/$siteId/blog/': typeof AuthenticatedSitesSiteIdBlogIndexRoute
  '/_authenticated/sites/$siteId/forms/': typeof AuthenticatedSitesSiteIdFormsIndexRoute
  '/_authenticated/sites/$siteId/menus/': typeof AuthenticatedSitesSiteIdMenusIndexRoute
  '/_authenticated/sites/$siteId/orders/': typeof AuthenticatedSitesSiteIdOrdersIndexRoute
  '/_authenticated/sites/$siteId/pages/': typeof AuthenticatedSitesSiteIdPagesIndexRoute
  '/_authenticated/sites/$siteId/products/': typeof AuthenticatedSitesSiteIdProductsIndexRoute
  '/_authenticated/sites/$siteId/workflows/': typeof AuthenticatedSitesSiteIdWorkflowsIndexRoute
  '/_authenticated/sites/$siteId/blog/$postId/edit': typeof AuthenticatedSitesSiteIdBlogPostIdEditRoute
  '/_authenticated/sites/$siteId/forms/$formId/edit': typeof AuthenticatedSitesSiteIdFormsFormIdEditRoute
  '/_authenticated/sites/$siteId/forms/$formId/submissions': typeof AuthenticatedSitesSiteIdFormsFormIdSubmissionsRoute
  '/_authenticated/sites/$siteId/pages/$pageId/edit': typeof AuthenticatedSitesSiteIdPagesPageIdEditRoute
  '/_authenticated/sites/$siteId/products/$productId/edit': typeof AuthenticatedSitesSiteIdProductsProductIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/api/auth/$'
    | '/s/$siteSlug/$'
    | '/dashboard/'
    | '/s/$siteSlug/'
    | '/sites/$siteId/edit'
    | '/s/$siteSlug/blog/$slug'
    | '/s/$siteSlug/f/$formKey'
    | '/s/$siteSlug/shop/$slug'
    | '/s/$siteSlug/blog/'
    | '/s/$siteSlug/shop/'
    | '/sites/$siteId/blog/'
    | '/sites/$siteId/forms/'
    | '/sites/$siteId/menus/'
    | '/sites/$siteId/orders/'
    | '/sites/$siteId/pages/'
    | '/sites/$siteId/products/'
    | '/sites/$siteId/workflows/'
    | '/sites/$siteId/blog/$postId/edit'
    | '/sites/$siteId/forms/$formId/edit'
    | '/sites/$siteId/forms/$formId/submissions'
    | '/sites/$siteId/pages/$pageId/edit'
    | '/sites/$siteId/products/$productId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/api/auth/$'
    | '/s/$siteSlug/$'
    | '/dashboard'
    | '/s/$siteSlug'
    | '/sites/$siteId/edit'
    | '/s/$siteSlug/blog/$slug'
    | '/s/$siteSlug/f/$formKey'
    | '/s/$siteSlug/shop/$slug'
    | '/s/$siteSlug/blog'
    | '/s/$siteSlug/shop'
    | '/sites/$siteId/blog'
    | '/sites/$siteId/forms'
    | '/sites/$siteId/menus'
    | '/sites/$siteId/orders'
    | '/sites/$siteId/pages'
    | '/sites/$siteId/products'
    | '/sites/$siteId/workflows'
    | '/sites/$siteId/blog/$postId/edit'
    | '/sites/$siteId/forms/$formId/edit'
    | '/sites/$siteId/forms/$formId/submissions'
    | '/sites/$siteId/pages/$pageId/edit'
    | '/sites/$siteId/products/$productId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/api/auth/$'
    | '/s/$siteSlug/$'
    | '/_authenticated/dashboard/'
    | '/s/$siteSlug/'
    | '/_authenticated/sites/$siteId/edit'
    | '/s/$siteSlug/blog/$slug'
    | '/s/$siteSlug/f/$formKey'
    | '/s/$siteSlug/shop/$slug'
    | '/s/$siteSlug/blog/'
    | '/s/$siteSlug/shop/'
    | '/_authenticated/sites/$siteId/blog/'
    | '/_authenticated/sites/$siteId/forms/'
    | '/_authenticated/sites/$siteId/menus/'
    | '/_authenticated/sites/$siteId/orders/'
    | '/_authenticated/sites/$siteId/pages/'
    | '/_authenticated/sites/$siteId/products/'
    | '/_authenticated/sites/$siteId/workflows/'
    | '/_authenticated/sites/$siteId/blog/$postId/edit'
    | '/_authenticated/sites/$siteId/forms/$formId/edit'
    | '/_authenticated/sites/$siteId/forms/$formId/submissions'
    | '/_authenticated/sites/$siteId/pages/$pageId/edit'
    | '/_authenticated/sites/$siteId/products/$productId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  SSiteSlugSplatRoute: typeof SSiteSlugSplatRoute
  SSiteSlugIndexRoute: typeof SSiteSlugIndexRoute
  SSiteSlugBlogSlugRoute: typeof SSiteSlugBlogSlugRoute
  SSiteSlugFFormKeyRoute: typeof SSiteSlugFFormKeyRoute
  SSiteSlugShopSlugRoute: typeof SSiteSlugShopSlugRoute
  SSiteSlugBlogIndexRoute: typeof SSiteSlugBlogIndexRoute
  SSiteSlugShopIndexRoute: typeof SSiteSlugShopIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$siteSlug/': {
      id: '/s/$siteSlug/'
      path: '/s/$siteSlug'
      fullPath: '/s/$siteSlug/'
      preLoaderRoute: typeof SSiteSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/s/$siteSlug/$': {
      id: '/s/$siteSlug/$'
      path: '/s/$siteSlug/$'
      fullPath: '/s/$siteSlug/$'
      preLoaderRoute: typeof SSiteSlugSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$siteSlug/shop/': {
      id: '/s/$siteSlug/shop/'
      path: '/s/$siteSlug/shop'
      fullPath: '/s/$siteSlug/shop/'
      preLoaderRoute: typeof SSiteSlugShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$siteSlug/blog/': {
      id: '/s/$siteSlug/blog/'
      path: '/s/$siteSlug/blog'
      fullPath: '/s/$siteSlug/blog/'
      preLoaderRoute: typeof SSiteSlugBlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$siteSlug/shop/$slug': {
      id: '/s/$siteSlug/shop/$slug'
      path: '/s/$siteSlug/shop/$slug'
      fullPath: '/s/$siteSlug/shop/$slug'
      preLoaderRoute: typeof SSiteSlugShopSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$siteSlug/f/$formKey': {
      id: '/s/$siteSlug/f/$formKey'
      path: '/s/$siteSlug/f/$formKey'
      fullPath: '/s/$siteSlug/f/$formKey'
      preLoaderRoute: typeof SSiteSlugFFormKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$siteSlug/blog/$slug': {
      id: '/s/$siteSlug/blog/$slug'
      path: '/s/$siteSlug/blog/$slug'
      fullPath: '/s/$siteSlug/blog/$slug'
      preLoaderRoute: typeof SSiteSlugBlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sites/$siteId/edit': {
      id: '/_authenticated/sites/$siteId/edit'
      path: '/sites/$siteId/edit'
      fullPath: '/sites/$siteId/edit'
      preLoaderRoute: typeof AuthenticatedSitesSiteIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sites/$siteId/workflows/': {
      id: '/_authenticated/sites/$siteId/workflows/'
      path: '/sites/$siteId/workflows'
      fullPath: '/sites/$siteId/workflows/'
      preLoaderRoute: typeof AuthenticatedSitesSiteIdWorkflowsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sites/$siteId/products/': {
      id: '/_authenticated/sites/$siteId/products/'
      path: '/sites/$siteId/products'
      fullPath: '/sites/$siteId/products/'
      preLoaderRoute: typeof AuthenticatedSitesSiteIdProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sites/$siteId/pages/': {
      id: '/_authenticated/sites/$siteId/pages/'
      path: '/sites/$siteId/pages'
      fullPath: '/sites/$siteId/pages/'
      preLoaderRoute: typeof AuthenticatedSitesSiteIdPagesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sites/$siteId/orders/': {
      id: '/_authenticated/sites/$siteId/orders/'
      path: '/sites/$siteId/orders'
      fullPath: '/sites/$siteId/orders/'
      preLoaderRoute: typeof AuthenticatedSitesSiteIdOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sites/$siteId/menus/': {
      id: '/_authenticated/sites/$siteId/menus/'
      path: '/sites/$siteId/menus'
      fullPath: '/sites/$siteId/menus/'
      preLoaderRoute: typeof AuthenticatedSitesSiteIdMenusIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sites/$siteId/forms/': {
      id: '/_authenticated/sites/$siteId/forms/'
      path: '/sites/$siteId/forms'
      fullPath: '/sites/$siteId/forms/'
      preLoaderRoute: typeof AuthenticatedSitesSiteIdFormsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sites/$siteId/blog/': {
      id: '/_authenticated/sites/$siteId/blog/'
      path: '/sites/$siteId/blog'
      fullPath: '/sites/$siteId/blog/'
      preLoaderRoute: typeof AuthenticatedSitesSiteIdBlogIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sites/$siteId/products/$productId/edit': {
      id: '/_authenticated/sites/$siteId/products/$productId/edit'
      path: '/sites/$siteId/products/$productId/edit'
      fullPath: '/sites/$siteId/products/$productId/edit'
      preLoaderRoute: typeof AuthenticatedSitesSiteIdProductsProductIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sites/$siteId/pages/$pageId/edit': {
      id: '/_authenticated/sites/$siteId/pages/$pageId/edit'
      path: '/sites/$siteId/pages/$pageId/edit'
      fullPath: '/sites/$siteId/pages/$pageId/edit'
      preLoaderRoute: typeof AuthenticatedSitesSiteIdPagesPageIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sites/$siteId/forms/$formId/submissions': {
      id: '/_authenticated/sites/$siteId/forms/$formId/submissions'
      path: '/sites/$siteId/forms/$formId/submissions'
      fullPath: '/sites/$siteId/forms/$formId/submissions'
      preLoaderRoute: typeof AuthenticatedSitesSiteIdFormsFormIdSubmissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sites/$siteId/forms/$formId/edit': {
      id: '/_authenticated/sites/$siteId/forms/$formId/edit'
      path: '/sites/$siteId/forms/$formId/edit'
      fullPath: '/sites/$siteId/forms/$formId/edit'
      preLoaderRoute: typeof AuthenticatedSitesSiteIdFormsFormIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sites/$siteId/blog/$postId/edit': {
      id: '/_authenticated/sites/$siteId/blog/$postId/edit'
      path: '/sites/$siteId/blog/$postId/edit'
      fullPath: '/sites/$siteId/blog/$postId/edit'
      preLoaderRoute: typeof AuthenticatedSitesSiteIdBlogPostIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedSitesSiteIdEditRoute: typeof AuthenticatedSitesSiteIdEditRoute
  AuthenticatedSitesSiteIdBlogIndexRoute: typeof AuthenticatedSitesSiteIdBlogIndexRoute
  AuthenticatedSitesSiteIdFormsIndexRoute: typeof AuthenticatedSitesSiteIdFormsIndexRoute
  AuthenticatedSitesSiteIdMenusIndexRoute: typeof AuthenticatedSitesSiteIdMenusIndexRoute
  AuthenticatedSitesSiteIdOrdersIndexRoute: typeof AuthenticatedSitesSiteIdOrdersIndexRoute
  AuthenticatedSitesSiteIdPagesIndexRoute: typeof AuthenticatedSitesSiteIdPagesIndexRoute
  AuthenticatedSitesSiteIdProductsIndexRoute: typeof AuthenticatedSitesSiteIdProductsIndexRoute
  AuthenticatedSitesSiteIdWorkflowsIndexRoute: typeof AuthenticatedSitesSiteIdWorkflowsIndexRoute
  AuthenticatedSitesSiteIdBlogPostIdEditRoute: typeof AuthenticatedSitesSiteIdBlogPostIdEditRoute
  AuthenticatedSitesSiteIdFormsFormIdEditRoute: typeof AuthenticatedSitesSiteIdFormsFormIdEditRoute
  AuthenticatedSitesSiteIdFormsFormIdSubmissionsRoute: typeof AuthenticatedSitesSiteIdFormsFormIdSubmissionsRoute
  AuthenticatedSitesSiteIdPagesPageIdEditRoute: typeof AuthenticatedSitesSiteIdPagesPageIdEditRoute
  AuthenticatedSitesSiteIdProductsProductIdEditRoute: typeof AuthenticatedSitesSiteIdProductsProductIdEditRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedSitesSiteIdEditRoute: AuthenticatedSitesSiteIdEditRoute,
  AuthenticatedSitesSiteIdBlogIndexRoute:
    AuthenticatedSitesSiteIdBlogIndexRoute,
  AuthenticatedSitesSiteIdFormsIndexRoute:
    AuthenticatedSitesSiteIdFormsIndexRoute,
  AuthenticatedSitesSiteIdMenusIndexRoute:
    AuthenticatedSitesSiteIdMenusIndexRoute,
  AuthenticatedSitesSiteIdOrdersIndexRoute:
    AuthenticatedSitesSiteIdOrdersIndexRoute,
  AuthenticatedSitesSiteIdPagesIndexRoute:
    AuthenticatedSitesSiteIdPagesIndexRoute,
  AuthenticatedSitesSiteIdProductsIndexRoute:
    AuthenticatedSitesSiteIdProductsIndexRoute,
  AuthenticatedSitesSiteIdWorkflowsIndexRoute:
    AuthenticatedSitesSiteIdWorkflowsIndexRoute,
  AuthenticatedSitesSiteIdBlogPostIdEditRoute:
    AuthenticatedSitesSiteIdBlogPostIdEditRoute,
  AuthenticatedSitesSiteIdFormsFormIdEditRoute:
    AuthenticatedSitesSiteIdFormsFormIdEditRoute,
  AuthenticatedSitesSiteIdFormsFormIdSubmissionsRoute:
    AuthenticatedSitesSiteIdFormsFormIdSubmissionsRoute,
  AuthenticatedSitesSiteIdPagesPageIdEditRoute:
    AuthenticatedSitesSiteIdPagesPageIdEditRoute,
  AuthenticatedSitesSiteIdProductsProductIdEditRoute:
    AuthenticatedSitesSiteIdProductsProductIdEditRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  SSiteSlugSplatRoute: SSiteSlugSplatRoute,
  SSiteSlugIndexRoute: SSiteSlugIndexRoute,
  SSiteSlugBlogSlugRoute: SSiteSlugBlogSlugRoute,
  SSiteSlugFFormKeyRoute: SSiteSlugFFormKeyRoute,
  SSiteSlugShopSlugRoute: SSiteSlugShopSlugRoute,
  SSiteSlugBlogIndexRoute: SSiteSlugBlogIndexRoute,
  SSiteSlugShopIndexRoute: SSiteSlugShopIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
