/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SSiteSlugIndexRouteImport } from './routes/s.$siteSlug.index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as SSiteSlugSplatRouteImport } from './routes/s.$siteSlug.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedSitesSiteIdEditRouteImport } from './routes/_authenticated/sites.$siteId.edit'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SSiteSlugIndexRoute = SSiteSlugIndexRouteImport.update({
  id: '/s/$siteSlug/',
  path: '/s/$siteSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const SSiteSlugSplatRoute = SSiteSlugSplatRouteImport.update({
  id: '/s/$siteSlug/$',
  path: '/s/$siteSlug/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSitesSiteIdEditRoute =
  AuthenticatedSitesSiteIdEditRouteImport.update({
    id: '/sites/$siteId/edit',
    path: '/sites/$siteId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/s/$siteSlug/$': typeof SSiteSlugSplatRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/s/$siteSlug/': typeof SSiteSlugIndexRoute
  '/sites/$siteId/edit': typeof AuthenticatedSitesSiteIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/s/$siteSlug/$': typeof SSiteSlugSplatRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/s/$siteSlug': typeof SSiteSlugIndexRoute
  '/sites/$siteId/edit': typeof AuthenticatedSitesSiteIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/s/$siteSlug/$': typeof SSiteSlugSplatRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/s/$siteSlug/': typeof SSiteSlugIndexRoute
  '/_authenticated/sites/$siteId/edit': typeof AuthenticatedSitesSiteIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/api/auth/$'
    | '/s/$siteSlug/$'
    | '/dashboard/'
    | '/s/$siteSlug/'
    | '/sites/$siteId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/api/auth/$'
    | '/s/$siteSlug/$'
    | '/dashboard'
    | '/s/$siteSlug'
    | '/sites/$siteId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/api/auth/$'
    | '/s/$siteSlug/$'
    | '/_authenticated/dashboard/'
    | '/s/$siteSlug/'
    | '/_authenticated/sites/$siteId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  SSiteSlugSplatRoute: typeof SSiteSlugSplatRoute
  SSiteSlugIndexRoute: typeof SSiteSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$siteSlug/': {
      id: '/s/$siteSlug/'
      path: '/s/$siteSlug'
      fullPath: '/s/$siteSlug/'
      preLoaderRoute: typeof SSiteSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/s/$siteSlug/$': {
      id: '/s/$siteSlug/$'
      path: '/s/$siteSlug/$'
      fullPath: '/s/$siteSlug/$'
      preLoaderRoute: typeof SSiteSlugSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sites/$siteId/edit': {
      id: '/_authenticated/sites/$siteId/edit'
      path: '/sites/$siteId/edit'
      fullPath: '/sites/$siteId/edit'
      preLoaderRoute: typeof AuthenticatedSitesSiteIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedSitesSiteIdEditRoute: typeof AuthenticatedSitesSiteIdEditRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedSitesSiteIdEditRoute: AuthenticatedSitesSiteIdEditRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  SSiteSlugSplatRoute: SSiteSlugSplatRoute,
  SSiteSlugIndexRoute: SSiteSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
